import java.util.Scanner;

/**
 * A simple random generator is obtained by the formula:
 * 
 * 		r[new] = (a * r[old] + b) % m
 * 
 * and then setting r[old] to r[new]. If m is chosen as 2^32, then you can compute
 * 		
 * 		r[new] = a * r[old] + b
 * 
 * because the truncation of an overflowing result to the int type is equivalent to
 * computing the remainder.
 * 
 * Write a program that asks the user to enter a value for r[old]. (Such a value is often
 * called a seed). Then print the first 100 random integers generated by this formula,
 * using a = 32310901 and b = 1729
 * 
 * @author Mayuresh
 *
 */
public class RandomGenerator
{
	public static void main(String[] args)
	{
		final int a = 32310901;
		final int b = 1729;
		
		int seed, m;
		
		Scanner in = new Scanner(System.in);
		
		System.out.print("Enter seed: ");
		seed = in.nextInt();
		
		System.out.println("Enter m: ");
		m = in.nextInt();
		
		in.close();
		
		for(int i = 1; i <= 100; i++)
		{
			int newVal = ((a * seed) + b);
			seed = newVal;

			System.out.println("RandInt #" + i + " = " + newVal);
		}
		
	}
}